name: MMDT Simple ETL pipeline
on:
  # push:
  #   branches:
  #     - main
  schedule:
    - cron: "0 21 12 4 *" ## Trigger on April 12 - 9PM (Default - UTC Timezone)
  workflow_dispatch: ## manual trigger

permissions:
  contents: write

jobs:
  simple-etl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo content
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Print secrets
        run: echo ${{ secrets.WEATHER_KEY }}
      - name: Run data pipeline
        run: python week9_demo/etl_demo.py
        env:
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          sqlite: ${{ secrets.SQLITE }}
      - name: Push saved sqlite db
        run: |
          git config user.name "Github Actions"
          git config user.email "actions@users.noreply.github.com"
          git add ./w10_demo.db
          git commit -m "Result sqlite db" && git push || true
